- name: copy yii2
  copy:
    src: "files/yii2.zip"
    dest: /tmp

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/yii2.zip
    dest: /opt
    remote_src: yes

- name: copy all config
  copy: 
    src: files/{{ item }} 
    dest: /opt/yii2/{{ item }}
  with_items:
    - Dockerfile
    - site.conf
    - docker-compose.yml

- name: Run `docker-compose up` again
  docker_compose:
    project_src: /opt/yii2
    build: yes
  register: output