version: '3'
services:
  php:
    build: .
#      dockerfile: Dockerfile  
    image: nginx-php-fpm  
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/var/www/app:delegated
    ports:
      - '80:80'
    depends_on:
      -  mysql
  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 33060:3306

